#! /bin/sh

################################################################################
#
#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/
#
#
################################################################################


###########################
## auto start ##
###########################

## keybind daemon
pkill sxhkd
sxhkd &

## polybar
$HOME/.config/polybar/launch.sh

## wallpaper
nitrogen --restore &

## window compositor
picom &

###########################
## General Configuration ##
###########################

## monitor
bspc monitor -d 1 2 3 4 5

## common bspwm config
bspc config border_width                0 
bspc config window_gap                  8
bspc config top_padding                 20
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true

## BSPWM coloring
bspc config normal_border_color		      "#febdf7"
bspc config active_border_color	          "#eff27c"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

## polybar hidden when fullscreen for vlc, youtube, mpv ...
## find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)

## Bspwm rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Zathura state=tiled
