# Prompt on new line
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

# prompt prefix
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\uF553 "

# add new line
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# icons
POWERLEVEL9K_HOME_ICON=$'\uE234'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable_joined custom_git_pair vcs_joined)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time ssh anaconda)

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uE252 %m.%d}"
